[package]
name = "tokenblitz"
version = "0.1.0"
edition = "2021"

[lib]
name = "tokenblitz"
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[[bin]]
name = "tokenblitz-cli"
path = "src/main.rs"

[dependencies]
pyo3 = { version = "0.20.0", features = ["extension-module"] }
